### ISSUE TITLE
New account registration

### ISSUE THREAD

**Issue by danilg3044** [shred/acme4j#150]
Hi there, I tried to register a new account with Buypass and Google Trust Services ACME servers and it did not work.
Bypass return HTTP status 400, and GTS - 403.
Certbot works in both cases.
The same code works fine with LetsEncrypt, ZeroSSL, Digicert and Globalsign ACME servers, and does not work with Buypass and GTS.
Please help.

Thank you.

**Comment by danilg3044** [comment]
The servers are
https://api.buypass.com/acme/directory
https://dv.acme-v02.api.pki.goog/directory

**Comment by shred** [comment]
GTS requires External Account Binding. Maybe Buypass too? See here: https://shredzone.org/maven/acme4j/usage/account.html#external-account-binding

You could also enable debugging and check if you get more information from the servers. https://shredzone.org/maven/acme4j/usage/debugging.html

**Comment by renfei** [comment]
I also got a 403 error when using Google Trust Services(GTS): ```External Account Binding JWS verification failed```

I use the staging environment for testing: https://dv.acme-v02.test-api.pki.goog/directory

```
org.shredzone.acme4j.AccountBuilder      : create
o.s.acme4j.connector.DefaultConnection   : GET https://dv.acme-v02.test-api.pki.goog/directory
o.s.acme4j.connector.DefaultConnection   : HEADER :status: 200
o.s.acme4j.connector.DefaultConnection   : HEADER alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
o.s.acme4j.connector.DefaultConnection   : HEADER cache-control: private
o.s.acme4j.connector.DefaultConnection   : HEADER content-encoding: gzip
o.s.acme4j.connector.DefaultConnection   : HEADER content-length: 240
o.s.acme4j.connector.DefaultConnection   : HEADER content-type: application/json
o.s.acme4j.connector.DefaultConnection   : HEADER date: Fri, 13 Sep 2024 06:46:59 GMT
o.s.acme4j.connector.DefaultConnection   : HEADER replay-nonce: AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjjv4-3BhCdrJKtAxDAxvS1-P____8BAM0v_oH8bp7Qfy_zTbX4IXk1tJ8AGw6ewg
o.s.acme4j.connector.DefaultConnection   : HEADER server: scaffolding on HTTPServer2
o.s.acme4j.connector.DefaultConnection   : HEADER x-frame-options: SAMEORIGIN
o.s.acme4j.connector.DefaultConnection   : HEADER x-xss-protection: 0
o.s.acme4j.connector.DefaultConnection   : Replay Nonce: AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjjv4-3BhCdrJKtAxDAxvS1-P____8BAM0v_oH8bp7Qfy_zTbX4IXk1tJ8AGw6ewg
o.s.acme4j.connector.DefaultConnection   : Replay Nonce: AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjjv4-3BhCdrJKtAxDAxvS1-P____8BAM0v_oH8bp7Qfy_zTbX4IXk1tJ8AGw6ewg
o.s.acme4j.connector.DefaultConnection   : Result JSON: {"newNonce":"https://dv.acme-v02.test-api.pki.goog/new-nonce","newAccount":"https://dv.acme-v02.test-api.pki.goog/new-account","newOrder":"https://dv.acme-v02.test-api.pki.goog/new-order","newAuthz":"https://dv.acme-v02.test-api.pki.goog/new-authz","revokeCert":"https://dv.acme-v02.test-api.pki.goog/revoke-cert","keyChange":"https://dv.acme-v02.test-api.pki.goog/key-change","renewalInfo":"https://dv.acme-v02.test-api.pki.goog/renewal-info","meta":{"termsOfService":"https://pki.goog/GTS-SA.pdf","website":"https://pki.goog","caaIdentities":["pki.goog"],"externalAccountRequired":true}}
org.shredzone.acme4j.toolbox.JoseUtils   : POST https://dv.acme-v02.test-api.pki.goog/new-account
org.shredzone.acme4j.toolbox.JoseUtils   :   Payload: {"contact":["mailto:i@renfei.net"],"termsOfServiceAgreed":true,"externalAccountBinding":{"protected":"eyJ1cmwiOiJodHRwczovL2R2LmFjbWUtdjAyLnRlc3QtYXBpLnBraS5nb29nL25ldy1hY2NvdW50Iiwia2lkIjoiNTE0ZmE5NTk0YTRhMjQ4MGU1YTYwZGVkYzQ1ZmFlZjQiLCJhbGciOiJIUzI1NiJ9","signature":"h_Su-l1XxjxK-3-bjO0SzRL80JDIVxszG3m_vuzakXs","payload":"eyJrdHkiOiJFQyIsIngiOiI3cm5ZUFNIMGZWaTBhSy1NV2tBN0dXbk1OclVpNDlOVmczVVdfZ0U0M3NoVDlsbHZNOW1GbE1CUTMzNkU1WUlmIiwieSI6InhoUllTc1p1bXJZN3cxTEpETzM1Y1N2UmUwcW9Vb3RTX1UxUy11ZXJPN3RrNXI1ZGthUkR6eDg2ZHQwS2N5eEEiLCJjcnYiOiJQLTM4NCJ9"}}
org.shredzone.acme4j.toolbox.JoseUtils   :   JWS Header: {"url":"https://dv.acme-v02.test-api.pki.goog/new-account","jwk":{"kty":"EC","x":"7rnYPSH0fVi0aK-MWkA7GWnMNrUi49NVg3UW_gE43shT9llvM9mFlMBQ336E5YIf","y":"xhRYSsZumrY7w1LJDO35cSvRe0qoUotS_U1S-uerO7tk5r5dkaRDzx86dt0KcyxA","crv":"P-384"},"nonce":"AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjjv4-3BhCdrJKtAxDAxvS1-P____8BAM0v_oH8bp7Qfy_zTbX4IXk1tJ8AGw6ewg","alg":"ES384"}
o.s.acme4j.connector.DefaultConnection   : HEADER :status: 403
o.s.acme4j.connector.DefaultConnection   : HEADER alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
o.s.acme4j.connector.DefaultConnection   : HEADER content-length: 147
o.s.acme4j.connector.DefaultConnection   : HEADER content-type: application/problem+json
o.s.acme4j.connector.DefaultConnection   : HEADER date: Fri, 13 Sep 2024 06:47:01 GMT
o.s.acme4j.connector.DefaultConnection   : HEADER link: <https://dv.acme-v02.test-api.pki.goog/directory>;rel="index"
o.s.acme4j.connector.DefaultConnection   : HEADER replay-nonce: AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjlv4-3BhDpzLayARDe773W______8BAM0v_oG_dFvLxMJZ7XNQsfBYRUMIrGGuvg
o.s.acme4j.connector.DefaultConnection   : HEADER server: scaffolding on HTTPServer2
o.s.acme4j.connector.DefaultConnection   : HEADER x-frame-options: SAMEORIGIN
o.s.acme4j.connector.DefaultConnection   : HEADER x-xss-protection: 0
o.s.acme4j.connector.DefaultConnection   : Replay Nonce: AEkAAAAKRwoqdHlwZS5nb29nbGVhcGlzLmNvbS9zZWN1cml0eV90YXJzaWVyLk5vbmNlEhkKDAjlv4-3BhDpzLayARDe773W______8BAM0v_oG_dFvLxMJZ7XNQsfBYRUMIrGGuvg
o.s.acme4j.connector.DefaultConnection   : Result JSON: {"type":"urn:ietf:params:acme:error:unauthorized","detail":"External Account Binding JWS verification failed","requestID":"-Sgjz71MidR6I6SDo2tlCw"}

org.shredzone.acme4j.exception.AcmeUnauthorizedException: External Account Binding JWS verification failed

	at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:528)
	at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:446)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:383)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:207)
	at org.shredzone.acme4j.AccountBuilder.createLogin(AccountBuilder.java:290)
	at org.shredzone.acme4j.AccountBuilder.create(AccountBuilder.java:249)

```

**Comment by shred** [comment]
The log file is looking good so far. I will try to reproduce the issue, but I won't be able to make it before Monday.

In the meantime, please make sure that you did not mix up the `keyId` and `b64MacKey` parameters. `withKeyIdentifier()` expects the KID as first, and the mac key as second parameter.

Also, according to the Google documentation you cannot use a production account key for registering on the staging server, but you must use `gcloud config set api_endpoint_overrides/publicca https://preprod-publicca.googleapis.com/` to switch to the staging environment, and then create a separate account key.

**Comment by shred** [comment]
I had to explicitly set `accountBuilder.withMacAlgorithm("HS256")`. But then I was able to create an account at https://dv.acme-v02.test-api.pki.goog/directory using the KID and MAC key that was provided by Google.

I'm sorry, but I can't reproduce your issue here.

**Comment by renfei** [comment]
Thanks for your reply.

Could you please add the example code of Google Trust Services(GTS) in [https://shredzone.org/maven/acme4j/ca/index.html](https://shredzone.org/maven/acme4j/ca/index.html) ?

Here is my code:

> I mainly modified the findOrRegisterAccount method.

### pom.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.renfei</groupId>
    <artifactId>acme4j-gts</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.shredzone.acme4j</groupId>
            <artifactId>acme4j-client</artifactId>
            <version>3.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-apikeys</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-publicca</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.13</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>26.45.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
```

### Java

```java
package net.renfei;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.security.KeyPair;
import java.security.Security;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Optional;
import java.util.function.Supplier;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

import com.google.cloud.security.publicca.v1.*;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.shredzone.acme4j.Account;
import org.shredzone.acme4j.AccountBuilder;
import org.shredzone.acme4j.Authorization;
import org.shredzone.acme4j.Certificate;
import org.shredzone.acme4j.Order;
import org.shredzone.acme4j.Problem;
import org.shredzone.acme4j.Session;
import org.shredzone.acme4j.Status;
import org.shredzone.acme4j.challenge.Challenge;
import org.shredzone.acme4j.challenge.Dns01Challenge;
import org.shredzone.acme4j.challenge.Http01Challenge;
import org.shredzone.acme4j.exception.AcmeException;
import org.shredzone.acme4j.util.KeyPairUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    // Set the Connection URI of your CA here. For testing purposes, use a staging
    // server if possible. Example: "acme://letsencrypt.org/staging" for the Let's
    // Encrypt staging server.
    private static final String CA_URI = "https://dv.acme-v02.test-api.pki.goog/directory";

    // E-Mail address to be associated with the account. Optional, null if not used.
    private static final String ACCOUNT_EMAIL = "i@renfei.net";

    // A supplier for a new account KeyPair. The default creates a new EC key pair.
    private static Supplier<KeyPair> ACCOUNT_KEY_SUPPLIER = () -> KeyPairUtils.createKeyPair();

    // A supplier for a new domain KeyPair. The default creates a RSA key pair.
    private static Supplier<KeyPair> DOMAIN_KEY_SUPPLIER = () -> KeyPairUtils.createKeyPair(4096);

    // File name of the User Key Pair
    private static final File USER_KEY_FILE = new File("user.key");

    // File name of the Domain Key Pair
    private static final File DOMAIN_KEY_FILE = new File("domain.key");

    // File name of the signed certificate
    private static final File DOMAIN_CHAIN_FILE = new File("domain-chain.crt");

    //Challenge type to be used
    private static final ChallengeType CHALLENGE_TYPE = ChallengeType.HTTP;

    // Maximum time to wait until VALID/INVALID is expected
    private static final Duration TIMEOUT = Duration.ofSeconds(60L);

    private static final Logger LOG = LoggerFactory.getLogger(Main.class);

    private enum ChallengeType {HTTP, DNS}

    /**
     * Generates a certificate for the given domains. Also takes care for the registration
     * process.
     *
     * @param domains Domains to get a common certificate for
     */
    public void fetchCertificate(Collection<String> domains) throws IOException, AcmeException, InterruptedException {
        // Load the user key file. If there is no key file, create a new one.
        KeyPair userKeyPair = loadOrCreateUserKeyPair();

        // Create a session.
        Session session = new Session(CA_URI);

        // Get the Account.
        // If there is no account yet, create a new one.
        Account acct = findOrRegisterAccount(session, userKeyPair);

        // Load or create a key pair for the domains. This should not be the userKeyPair!
        KeyPair domainKeyPair = loadOrCreateDomainKeyPair();

        // Order the certificate
        Order order = acct.newOrder().domains(domains).create();

        // Perform all required authorizations
        for (Authorization auth : order.getAuthorizations()) {
            authorize(auth);
        }

        // Wait for the order to become READY
        order.waitUntilReady(TIMEOUT);

        // Order the certificate
        order.execute(domainKeyPair);

        // Wait for the order to complete
        Status status = order.waitForCompletion(TIMEOUT);
        if (status != Status.VALID) {
            LOG.error("Order has failed, reason: {}", order.getError()
                    .map(Problem::toString)
                    .orElse("unknown"));
            throw new AcmeException("Order failed... Giving up.");
        }

        // Get the certificate
        Certificate certificate = order.getCertificate();

        LOG.info("Success! The certificate for domains {} has been generated!", domains);
        LOG.info("Certificate URL: {}", certificate.getLocation());

        // Write a combined file containing the certificate and chain.
        try (FileWriter fw = new FileWriter(DOMAIN_CHAIN_FILE)) {
            certificate.writeCertificate(fw);
        }

        // That's all! Configure your web server to use the DOMAIN_KEY_FILE and
        // DOMAIN_CHAIN_FILE for the requested domains.
    }

    /**
     * Loads a user key pair from {@link #USER_KEY_FILE}. If the file does not exist, a
     * new key pair is generated and saved.
     * <p>
     * Keep this key pair in a safe place! In a production environment, you will not be
     * able to access your account again if you should lose the key pair.
     *
     * @return User's {@link KeyPair}.
     */
    private KeyPair loadOrCreateUserKeyPair() throws IOException {
        if (USER_KEY_FILE.exists()) {
            // If there is a key file, read it
            try (FileReader fr = new FileReader(USER_KEY_FILE)) {
                return KeyPairUtils.readKeyPair(fr);
            }

        } else {
            // If there is none, create a new key pair and save it
            KeyPair userKeyPair = ACCOUNT_KEY_SUPPLIER.get();
            try (FileWriter fw = new FileWriter(USER_KEY_FILE)) {
                KeyPairUtils.writeKeyPair(userKeyPair, fw);
            }
            return userKeyPair;
        }
    }

    /**
     * Loads a domain key pair from {@link #DOMAIN_KEY_FILE}. If the file does not exist,
     * a new key pair is generated and saved.
     *
     * @return Domain {@link KeyPair}.
     */
    private KeyPair loadOrCreateDomainKeyPair() throws IOException {
        if (DOMAIN_KEY_FILE.exists()) {
            try (FileReader fr = new FileReader(DOMAIN_KEY_FILE)) {
                return KeyPairUtils.readKeyPair(fr);
            }
        } else {
            KeyPair domainKeyPair = DOMAIN_KEY_SUPPLIER.get();
            try (FileWriter fw = new FileWriter(DOMAIN_KEY_FILE)) {
                KeyPairUtils.writeKeyPair(domainKeyPair, fw);
            }
            return domainKeyPair;
        }
    }

    /**
     * Finds your {@link Account} at the ACME server. It will be found by your user's
     * public key. If your key is not known to the server yet, a new account will be
     * created.
     * <p>
     * This is a simple way of finding your {@link Account}. A better way is to get the
     * URL of your new account with {@link Account#getLocation()} and store it somewhere.
     * If you need to get access to your account later, reconnect to it via {@link
     * Session#login(URL, KeyPair)} by using the stored location.
     *
     * @param session {@link Session} to bind with
     * @return {@link Account}
     */
    private Account findOrRegisterAccount(Session session, KeyPair accountKey) throws AcmeException, IOException {
        // Ask the user to accept the TOS, if server provides us with a link.
        Optional<URI> tos = session.getMetadata().getTermsOfService();
        if (tos.isPresent()) {
            acceptAgreement(tos.get());
        }

        AccountBuilder accountBuilder = new AccountBuilder()
                .agreeToTermsOfService()
                .withMacAlgorithm("HS256")
                .useKeyPair(accountKey);

        // Set your email (if available)
        if (ACCOUNT_EMAIL != null) {
            accountBuilder.addEmail(ACCOUNT_EMAIL);
        }

        // GTS
        PublicCertificateAuthorityServiceSettings publicCertificateAuthorityServiceSettings
                = PublicCertificateAuthorityServiceSettings.newBuilder()
                .setEndpoint("preprod-publicca.googleapis.com:443")
                .build();
        ExternalAccountKey externalAccountKey;
        try (PublicCertificateAuthorityServiceClient publicCertificateAuthorityServiceClient =
                     PublicCertificateAuthorityServiceClient.create(publicCertificateAuthorityServiceSettings)) {
            CreateExternalAccountKeyRequest request =
                    CreateExternalAccountKeyRequest.newBuilder()
                            .setParent(LocationName.of("ren-fei", "global").toString())
                            .setExternalAccountKey(ExternalAccountKey.newBuilder().build())
                            .build();
            externalAccountKey = publicCertificateAuthorityServiceClient.createExternalAccountKey(request);
        }
        SecretKey secretKey = new SecretKeySpec(externalAccountKey.getB64MacKey().toByteArray(), "HMAC");
        accountBuilder.withKeyIdentifier(externalAccountKey.getKeyId(), secretKey);

        Account account = accountBuilder.create(session);
        LOG.info("Registered a new user, URL: {}", account.getLocation());

        return account;
    }

    /**
     * Authorize a domain. It will be associated with your account, so you will be able to
     * retrieve a signed certificate for the domain later.
     *
     * @param auth {@link Authorization} to perform
     */
    private void authorize(Authorization auth) throws AcmeException, InterruptedException {
        LOG.info("Authorization for domain {}", auth.getIdentifier().getDomain());

        // The authorization is already valid. No need to process a challenge.
        if (auth.getStatus() == Status.VALID) {
            return;
        }

        // Find the desired challenge and prepare it.
        Challenge challenge = null;
        switch (CHALLENGE_TYPE) {
            case HTTP:
                challenge = httpChallenge(auth);
                break;

            case DNS:
                challenge = dnsChallenge(auth);
                break;
        }

        if (challenge == null) {
            throw new AcmeException("No challenge found");
        }

        // If the challenge is already verified, there's no need to execute it again.
        if (challenge.getStatus() == Status.VALID) {
            return;
        }

        // Now trigger the challenge.
        challenge.trigger();

        // Poll for the challenge to complete.
        Status status = challenge.waitForCompletion(TIMEOUT);
        if (status != Status.VALID) {
            LOG.error("Challenge has failed, reason: {}", challenge.getError()
                    .map(Problem::toString)
                    .orElse("unknown"));
            throw new AcmeException("Challenge failed... Giving up.");
        }

        LOG.info("Challenge has been completed. Remember to remove the validation resource.");
        completeChallenge("Challenge has been completed.\nYou can remove the resource again now.");
    }

    /**
     * Prepares a HTTP challenge.
     * <p>
     * The verification of this challenge expects a file with a certain content to be
     * reachable at a given path under the domain to be tested.
     * <p>
     * This example outputs instructions that need to be executed manually. In a
     * production environment, you would rather generate this file automatically, or maybe
     * use a servlet that returns {@link Http01Challenge#getAuthorization()}.
     *
     * @param auth {@link Authorization} to find the challenge in
     * @return {@link Challenge} to verify
     */
    public Challenge httpChallenge(Authorization auth) throws AcmeException {
        // Find a single http-01 challenge
        Http01Challenge challenge = auth.findChallenge(Http01Challenge.class)
                .orElseThrow(() -> new AcmeException("Found no " + Http01Challenge.TYPE
                        + " challenge, don't know what to do..."));

        // Output the challenge, wait for acknowledge...
        LOG.info("Please create a file in your web server's base directory.");
        LOG.info("It must be reachable at: http://{}/.well-known/acme-challenge/{}",
                auth.getIdentifier().getDomain(), challenge.getToken());
        LOG.info("File name: {}", challenge.getToken());
        LOG.info("Content: {}", challenge.getAuthorization());
        LOG.info("The file must not contain any leading or trailing whitespaces or line breaks!");
        LOG.info("If you're ready, dismiss the dialog...");

        StringBuilder message = new StringBuilder();
        message.append("Please create a file in your web server's base directory.\n\n");
        message.append("http://")
                .append(auth.getIdentifier().getDomain())
                .append("/.well-known/acme-challenge/")
                .append(challenge.getToken())
                .append("\n\n");
        message.append("Content:\n\n");
        message.append(challenge.getAuthorization());
        acceptChallenge(message.toString());

        return challenge;
    }

    /**
     * Prepares a DNS challenge.
     * <p>
     * The verification of this challenge expects a TXT record with a certain content.
     * <p>
     * This example outputs instructions that need to be executed manually. In a
     * production environment, you would rather configure your DNS automatically.
     *
     * @param auth {@link Authorization} to find the challenge in
     * @return {@link Challenge} to verify
     */
    public Challenge dnsChallenge(Authorization auth) throws AcmeException {
        // Find a single dns-01 challenge
        Dns01Challenge challenge = auth.findChallenge(Dns01Challenge.TYPE)
                .map(Dns01Challenge.class::cast)
                .orElseThrow(() -> new AcmeException("Found no " + Dns01Challenge.TYPE
                        + " challenge, don't know what to do..."));

        // Output the challenge, wait for acknowledge...
        LOG.info("Please create a TXT record:");
        LOG.info("{} IN TXT {}",
                Dns01Challenge.toRRName(auth.getIdentifier()), challenge.getDigest());
        LOG.info("If you're ready, dismiss the dialog...");

        StringBuilder message = new StringBuilder();
        message.append("Please create a TXT record:\n\n");
        message.append(Dns01Challenge.toRRName(auth.getIdentifier()))
                .append(" IN TXT ")
                .append(challenge.getDigest());
        acceptChallenge(message.toString());

        return challenge;
    }

    /**
     * Presents the instructions for preparing the challenge validation, and waits for
     * dismissal. If the user cancelled the dialog, an exception is thrown.
     *
     * @param message Instructions to be shown in the dialog
     */
    public void acceptChallenge(String message) throws AcmeException {
        int option = JOptionPane.showConfirmDialog(null,
                message,
                "Prepare Challenge",
                JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.CANCEL_OPTION) {
            throw new AcmeException("User cancelled the challenge");
        }
    }

    /**
     * Presents the instructions for removing the challenge validation, and waits for
     * dismissal.
     *
     * @param message Instructions to be shown in the dialog
     */
    public void completeChallenge(String message) {
        JOptionPane.showMessageDialog(null,
                message,
                "Complete Challenge",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Presents the user a link to the Terms of Service, and asks for confirmation. If the
     * user denies confirmation, an exception is thrown.
     *
     * @param agreement {@link URI} of the Terms of Service
     */
    public void acceptAgreement(URI agreement) throws AcmeException {
        int option = JOptionPane.showConfirmDialog(null,
                "Do you accept the Terms of Service?\n\n" + agreement,
                "Accept ToS",
                JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.NO_OPTION) {
            throw new AcmeException("User did not accept Terms of Service");
        }
    }

    /**
     * Invokes this example.
     *
     * @param args Domains to get a certificate for
     */
    public static void main(String... args) {
        LOG.info("Starting up...");

        Security.addProvider(new BouncyCastleProvider());

        Collection<String> domains = new ArrayList<>() {{
            this.add("renfei.net");
            this.add("*.renfei.net");
        }};
        try {
            Main ct = new Main();
            ct.fetchCertificate(domains);
        } catch (Exception ex) {
            LOG.error("Failed to get a certificate for domains " + domains, ex);
        }
    }
}
```

### Log

```text
[main] INFO net.renfei.Main - Starting up...
[main] ERROR net.renfei.Main - Failed to get a certificate for domains [renfei.net, *.renfei.net]
org.shredzone.acme4j.exception.AcmeUnauthorizedException: External Account Binding JWS verification failed
	at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:528)
	at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:446)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:383)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:207)
	at org.shredzone.acme4j.AccountBuilder.createLogin(AccountBuilder.java:290)
	at org.shredzone.acme4j.AccountBuilder.create(AccountBuilder.java:249)
	at net.renfei.Main.findOrRegisterAccount(Main.java:225)
	at net.renfei.Main.fetchCertificate(Main.java:88)
	at net.renfei.Main.main(Main.java:419)

Process finished with exit code 0
```

**Comment by shred** [comment]
What's still missing is setting the MAC algorithm:

```java
SecretKey secretKey = new SecretKeySpec(externalAccountKey.getB64MacKey().toByteArray(), "HMAC");
accountBuilder.withKeyIdentifier(externalAccountKey.getKeyId(), secretKey);

// Set MAC algorithm to HS256
accountBuilder.withMacAlgorithm("HS256");

Account account = accountBuilder.create(session);
LOG.info("Registered a new user, URL: {}", account.getLocation());
```

**Comment by renfei** [comment]
Hi.

I have already set it above:

```java
AccountBuilder accountBuilder = new AccountBuilder()
                .agreeToTermsOfService()
                .withMacAlgorithm("HS256")
                .useKeyPair(accountKey);
```

**Comment by shred** [comment]
I'm sorry... I missed that line in your code.

Anyway, when I try to execute your code, it fails at

```
PublicCertificateAuthorityServiceClient.create(publicCertificateAuthorityServiceSettings))
```

with the error "Your default credentials were not found. To set up Application Default Credentials for your environment, see https://cloud.google.com/docs/authentication/external/set-up-adc."

I don't have the time to dig deeper into the Google Cloud documentation and understand what's missing here.

I used this tutorial to manually create a staging key: https://cloud.google.com/certificate-manager/docs/public-ca-tutorial 

With the result set as `EAB_KID` and `EAB_HMAC`, I was able to create a new account (given the `HS256` Mac algorithm was set).

So maybe the problem is in your GTS code section, and a wrong key is generated there. Can you try to manually create a staging key and reproduce that problem on your side?

**Comment by shred** [comment]
I'm glad you got it working. :smile: 

I will add an acme4j provider for Google's CA and the corresponding documentation. Maybe I can also get rid of having to set `HS256` manually.

**Comment by shred** [comment]
About BuyPass: It does not seem to support the `secp384r1` key type that is generated by `KeyPair.createKeyPair()`. When I used an RSA keypair instead, I was able to create an account on the staging server.

I will add Google and BuyPass providers in the next acme4j release, to add some comfort.

However there are no actual issues in acme4j regarding these CAs, so I will close the issue now.
