### ISSUE TITLE
Problem with private key and netty SslContext

### ISSUE THREAD

**Issue by doom369** [shred/acme4j#31]
Hello. I've successfully generated certs on staging server using your Test client. However, I'm getting the error when try to use it on my server that uses Netty: 

```
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /home/doom369/IdeaProjects/acme4j/domain.key
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:252)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:207)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:50)
	... 8 more
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1001)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:970)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:250)
	... 12 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:999)
	... 14 more
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351)
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356)
	at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73)
	at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
	... 16 more
```

Generated private key and cert via certbot works fine: 

```
fullchain.pem
privkey.pem
```
However, this

```
domain-chain.crt
domain.key
```

doesn't.

Could you please advise?

**Comment by doom369** [comment]
Ok. I dig into your code and found that you are using BouncyCastle. So adding this to my code : 

```
        java.security.Security.addProvider(
                new BouncyCastleProvider()
        );
```

fixed the issue. I'll check if that could be avoided.
