### ISSUE TITLE
Exception with Data-URI in ToS

### ISSUE THREAD

**Issue by marsangr** [shred/acme4j#41]
Pebble delivers a Data-URI in Directory-Terms-Of-Service that acme4j is not able to process:

DEBUG 12:46:31,208 [] Link: terms-of-service -> data:text/plain,Do%20what%20thou%20wilt
org.shredzone.acme4j.exception.AcmeProtocolException: Cannot resolve relative link: data:text/plain,Do%20what%20thou%20wilt
	at org.shredzone.acme4j.connector.DefaultConnection.resolveRelative(DefaultConnection.java:456)
	at org.shredzone.acme4j.connector.DefaultConnection.getLinks(DefaultConnection.java:331)
	at org.shredzone.acme4j.connector.DefaultConnection.getLink(DefaultConnection.java:305)
	at org.shredzone.acme4j.connector.DefaultConnection.createAcmeException(DefaultConnection.java:392)
	at org.shredzone.acme4j.connector.DefaultConnection.accept(DefaultConnection.java:205)
	at org.shredzone.acme4j.RegistrationBuilder.create(RegistrationBuilder.java:87)

As far as I can tell, a Data-URI in that place is perfectly valid.

**Comment by shred** [comment]
According to the line numbers in the stack trace, you seem to use _acme4j_ with major version 0. It only implements the ACME v1 protocol.

Pebble is an ACME v2 server. You would need _acme4j_ from the [draft](/shred/acme4j/tree/draft) branch to connect to it. As the branch runs integration tests against Pebble, the bug should not occur there.

**Comment by marsangr** [comment]
That's true. Thanks.
