### ISSUE TITLE
org.shredzone.acme4j.exception.AcmeServerException: JWS verification error

### ISSUE THREAD

**Issue by eknori** [shred/acme4j#50]
I am using the acme-v2 in a Domino server OSGi plugin ( DOTS )
I am trying to get a certificate using the DNS Challenge. I do not have configured my DNS server, so it is expected that LE cannot verify the challenge. 
When I run my code for the first time, a new account is created and everything works as expected, incl. the challenge failure.

Running the code again, I get

```
org.shredzone.acme4j.exception.AcmeServerException: JWS verification error
	at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:446)
	at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:365)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:177)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:162)
	at org.shredzone.acme4j.OrderBuilder.create(OrderBuilder.java:151)
	at de.midpoints.le4d.manager.Le4dManager.orderCertificateUseDNSChallenge(Le4dManager.java:252)
	at de.midpoints.le4d.manager.Le4dManager.process(Le4dManager.java:160)
	at de.midpoints.le4d.manager.Le4dManager.run(Le4dManager.java:119)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:44)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:39)
	at de.midpoints.le4d.tools.SessionDatabase.runWithSessionAndDatabase(SessionDatabase.java:32)
	at de.midpoints.le4d.runonstart.Le4d.doRun(Le4d.java:39)
	at com.ibm.dots.task.AbstractServerTaskExt.run(AbstractServerTaskExt.java:47)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.doRun(JobTaskService.java:137)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.run(JobTaskService.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```
I have stored the information from acct.getLocation() during the first run and use it now to bind the session to the already existing acct.
```

[162C:0018-1104] 07.01.2018 10:13:47   [DOTS] midpoints.le4d - midpoints.le4d started.
[162C:0018-1104] 07.01.2018 10:13:47   [DOTS] midpoints.le4d - LE4D (c) 2017, V 2.0.0.20180107101218-d9bb306 - started!
[162C:0018-1104] 07.01.2018 10:13:47   [DOTS] midpoints.le4d - Requesting certificates.
[162C:0018-1104] 07.01.2018 10:13:47   [DOTS] midpoints.le4d - Running in staging mode
[162C:0018-1104] 07.01.2018 10:13:47   [DOTS] midpoints.le4d - Using existing account.
```
This also seems to work. 

line 252 in the stack trace corresponds to the following line of code.
`
Order order = account.newOrder().domains(domains).notBefore(notBefore).notAfter(notAfter).create();`

Similar code is being used for HTTP Challenge without any issue.

**Comment by shred** [comment]
"JWS verification error" means that the request failed because of a bad signature. Sadly, there is no further explanation of what actually couldn't get verified by the server.

A reason could be that the `Session` is in an inconsistent state. The `Session` contains the key pair of the account, and a matching _key identifier_. If you use `Account.bind()` or the `AccountBuilder()`, the key identifier is set automatically. However, if you create a new `Session` object and use it for binding a different resource (e.g. an order or a challenge), you must first set the key identifier yourself. For _Let's Encrypt_, the key identifier is just your account URL. So creating a new `Session` should work like this:

```java
URI serverUri = // your ACME server URI, e.g. "acme://letsencrypt.org"
KeyPair keyPair = // your account key pair
URL accountUrl = // the URL of your account, from Account.getLocation()

Session session = new Session(serverUri, keyPair);
session.setKeyIdentifier(accountUrl.toString());
```

I see that this part is missing in the documentation. I'm going to add it...

Does it work if you create a new session like that?

If not, please try to activate debug logging for _acme4j_. It uses _slf4j_ for logging.

**Comment by eknori** [comment]
here is the output from the DEBUG log

```
2018-08-01 10:06:55.971 DEBUG - create
2018-08-01 10:06:55.971 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/directory
2018-08-01 10:06:56.285 DEBUG - HEADER X-Frame-Options: DENY
2018-08-01 10:06:56.285 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-08-01 10:06:56.285 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-08-01 10:06:56.285 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-08-01 10:06:56.285 DEBUG - HEADER Server: nginx
2018-08-01 10:06:56.285 DEBUG - HEADER Replay-Nonce: UryKFBNFLsrUDGK9xwjf5lbaquivUghxDcz0iz6ZpmQ
2018-08-01 10:06:56.285 DEBUG - HEADER Connection: keep-alive
2018-08-01 10:06:56.285 DEBUG - HEADER Pragma: no-cache
2018-08-01 10:06:56.285 DEBUG - HEADER Expires: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.285 DEBUG - HEADER Content-Length: 602
2018-08-01 10:06:56.285 DEBUG - HEADER Date: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.285 DEBUG - HEADER Content-Type: application/json
2018-08-01 10:06:56.285 DEBUG - Replay Nonce: UryKFBNFLsrUDGK9xwjf5lbaquivUghxDcz0iz6ZpmQ
2018-08-01 10:06:56.285 DEBUG - Result JSON: {"keyChange":"https://acme-staging-v02.api.letsencrypt.org/acme/key-change","meta":{"termsOfService":"https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"},"newAccount":"https://acme-staging-v02.api.letsencrypt.org/acme/new-acct","newNonce":"https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce","newOrder":"https://acme-staging-v02.api.letsencrypt.org/acme/new-order","revokeCert":"https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert","tAyo-n4A_zo":"https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"}
2018-08-01 10:06:56.316 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/new-acct
2018-08-01 10:06:56.316 DEBUG -   Payload: {"termsOfServiceAgreed":true}
2018-08-01 10:06:56.316 DEBUG -   JWS Header: {"nonce":"UryKFBNFLsrUDGK9xwjf5lbaquivUghxDcz0iz6ZpmQ","url":"https://acme-staging-v02.api.letsencrypt.org/acme/new-acct","jwk":{"kty":"RSA","n":"yT5usyuk0Lv1lHNjXPzJI2hzf-SDskX20R1VS0cpVcOOJVhbRhY3e3xYlnEppPgeorlFYw0LHrcveDgbyurXenTRrqZwJNy9LUoeYwR6fwYv4d6S15cgGNUQq--neG5jshTY13PEj5R5Fr-fDDjRTMcpb7-LJMgeM1NTeHcDLyZSQZ7RLYKaiO5coJ0fKRsj6KNPbPTQGVsSqRVQ7gN3xIVaQTusbBmc2VyuIRm1vTOr7Nhb4fH2I54ciAPWHpnOBHRhVQgyRRwTuTRvdJcwJt8SF7Wjy_gOZKkxUVXnKFDrjlYubyZMhKCEqoB8BN0tbvwNgIMSxC78R94Ac2uEPw","e":"AQAB"},"alg":"RS256"}
2018-08-01 10:06:56.504 DEBUG - HEADER null: HTTP/1.1 409 Conflict
2018-08-01 10:06:56.504 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-08-01 10:06:56.504 DEBUG - HEADER Server: nginx
2018-08-01 10:06:56.504 DEBUG - HEADER Replay-Nonce: 4pnWrQP_-2N6zVW6Vts0fnBK-sA6y3ROQcJml4uhFkg
2018-08-01 10:06:56.504 DEBUG - HEADER Connection: close
2018-08-01 10:06:56.504 DEBUG - HEADER Pragma: no-cache
2018-08-01 10:06:56.519 DEBUG - HEADER Expires: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.519 DEBUG - HEADER Content-Length: 114
2018-08-01 10:06:56.519 DEBUG - HEADER Date: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.519 DEBUG - HEADER Location: https://acme-staging-v02.api.letsencrypt.org/acme/acct/5355059
2018-08-01 10:06:56.519 DEBUG - HEADER Content-Type: application/problem+json
2018-08-01 10:06:56.519 DEBUG - Replay Nonce: 4pnWrQP_-2N6zVW6Vts0fnBK-sA6y3ROQcJml4uhFkg
2018-08-01 10:06:56.519 DEBUG - Result JSON: {"type":"urn:ietf:params:acme:error:malformed","detail":"Account key is already in use","status":409}
2018-08-01 10:06:56.519 DEBUG - create
2018-08-01 10:06:56.535 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/new-order
2018-08-01 10:06:56.535 DEBUG -   Payload: {"identifiers":[{"type":"dns","value":"eknori.testdns.org"}],"notBefore":"2018-01-08T09:06:56.519Z","notAfter":"2018-01-28T09:06:56.519Z"}
2018-08-01 10:06:56.535 DEBUG -   JWS Header: {"nonce":"4pnWrQP_-2N6zVW6Vts0fnBK-sA6y3ROQcJml4uhFkg","url":"https://acme-staging-v02.api.letsencrypt.org/acme/new-order","kid":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/5345609","alg":"RS256"}
2018-08-01 10:06:56.785 DEBUG - HEADER null: HTTP/1.1 400 Bad Request
2018-08-01 10:06:56.785 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-08-01 10:06:56.785 DEBUG - HEADER Server: nginx
2018-08-01 10:06:56.785 DEBUG - HEADER Replay-Nonce: G1T0ILW_Agy43o3-GblUmjNlbUh-oEBmzHIteBk7wic
2018-08-01 10:06:56.785 DEBUG - HEADER Connection: close
2018-08-01 10:06:56.785 DEBUG - HEADER Pragma: no-cache
2018-08-01 10:06:56.800 DEBUG - HEADER Expires: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.800 DEBUG - HEADER Boulder-Requester: 5345609
2018-08-01 10:06:56.800 DEBUG - HEADER Content-Length: 107
2018-08-01 10:06:56.800 DEBUG - HEADER Date: Mon, 08 Jan 2018 09:06:56 GMT
2018-08-01 10:06:56.800 DEBUG - HEADER Content-Type: application/problem+json
2018-08-01 10:06:56.800 DEBUG - Replay Nonce: G1T0ILW_Agy43o3-GblUmjNlbUh-oEBmzHIteBk7wic
2018-08-01 10:06:56.816 DEBUG - Result JSON: {"type":"urn:ietf:params:acme:error:malformed","detail":"JWS verification error","status":400}

```

**Comment by eknori** [comment]
Found it, the stored value for KID was wrong.
The stored value is 5345609 but the correct value would be 5355059.

So, no issue with acme4Jv2

**Comment by shred** [comment]
Well, there is a conceptional issue with acme4jv2... The first create account call correctly returned a 409 Conflict, and a location header that points to the correct account id 5355059. acme4j should be able to handle this situation correctly, and at least return that location URL somewhere.

The Session, KID and existing account handling really needs some improvement.
