### ISSUE TITLE
ACME4Jv2 - java.io.IOException: Invalid keystore format

### ISSUE THREAD

**Issue by eknori** [shred/acme4j#51]
I try to use pebble for testing, but I cannot establish a connection because of the above error.
Any advice, how this can be fixed? 

Here is the complete stacktrace

```
org.shredzone.acme4j.exception.AcmeNetworkException: Network error
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:152)
	at org.shredzone.acme4j.provider.AbstractAcmeProvider.directory(AbstractAcmeProvider.java:53)
	at org.shredzone.acme4j.Session.readDirectory(Session.java:227)
	at org.shredzone.acme4j.Session.resourceUrl(Session.java:202)
	at org.shredzone.acme4j.AccountBuilder.create(AccountBuilder.java:163)
	at de.midpoints.le4d.manager.Le4dManager.orderCertificateUseDNSChallenge(Le4dManager.java:256)
	at de.midpoints.le4d.manager.Le4dManager.process(Le4dManager.java:163)
	at de.midpoints.le4d.manager.Le4dManager.run(Le4dManager.java:122)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:44)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:39)
	at de.midpoints.le4d.tools.SessionDatabase.runWithSessionAndDatabase(SessionDatabase.java:32)
	at de.midpoints.le4d.runonstart.Le4d.doRun(Le4d.java:39)
	at com.ibm.dots.task.AbstractServerTaskExt.run(AbstractServerTaskExt.java:47)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.doRun(JobTaskService.java:136)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.run(JobTaskService.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: Invalid keystore format
	at com.ibm.crypto.provider.JavaKeyStore.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1456)
	at org.shredzone.acme4j.provider.pebble.PebbleHttpConnector.createSocketFactory(PebbleHttpConnector.java:57)
	at org.shredzone.acme4j.provider.pebble.PebbleHttpConnector.openConnection(PebbleHttpConnector.java:44)
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:136)
	... 15 more
```

Linux is CentOS 7

```
java -version 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```
Update:

Domino uses its own JVM

```
./java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp22-20161213_02(SR3 FP22))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20161209_329148 (JIT enabled, AOT enabled)
J9VM - R28_20161209_1345_B329148
JIT  - tr.r14.java.green_20161207_128946
GC   - R28_20161209_1345_B329148_CMPRSS
J9CL - 20161209_329148)
JCL - 20161213_01 based on Oracle jdk8u111-b14
```

**Comment by shred** [comment]
acme4j uses a local keystore for the self-signed certificate used by the Pebble server. It seems that `com.ibm.crypto.provider.JavaKeyStore` is unable to read that keystore format.

I have tried to reproduce this error with Oracle JDK, OpenJDK and also OpenJ9, but the connection always succeeded. Maybe IBM's J9 or Domino expects a different keystore format, but I have no way to test that here.

Can you try to create your own pebble truststore with the `keytool` on your machine? You can find the [pebble.minica.pem here](https://raw.githubusercontent.com/letsencrypt/pebble/master/test/certs/pebble.minica.pem), and convert it with:

```bash
openssl x509 -outform der -in pebble.minica.pem -out pebble.minica.der
keytool -import -alias pebble -keystore pebble.truststore -file pebble.minica.der
```

The keystore password is `acme4j`. Copy the generated `pebble.truststore` file to `acme4j-client/src/main/resources/org/shredzone/acme4j/provider/pebble/pebble.truststore`.

**Comment by eknori** [comment]
I have checked the existing truststore with keytool. 
Next I created a new truststore as suggested and rebuilt the acme4j-client.2.0-SNAPSHOT

Rebuilt my project and now the error is gone. Will contact IBM regarding this issue.

```
C:\tools\OpenSSL\bin>keytool -list -keystore pebble.org.truststore
keytool error (likely untranslated): java.io.IOException: Invalid keystore format

C:\tools\OpenSSL\bin>keytool -list -keystore pebble.truststore
Enter keystore password:

Keystore type: jks
Keystore provider: IBMJCE

Your keystore contains 1 entry

pebble, Jan 9, 2018, trustedCertEntry,
Certificate fingerprint (SHA1): 3C:19:DA:2D:22:5C:FB:D7:C7:6B:CA:1B:FF:81:65:A2:42:02:8C:C2
```

**Comment by shred** [comment]
Can you give the pebble.truststore in the attached zip file a try? I created the original truststore with OpenJDK, and the attached truststore with Oracle JDK. Thanks!

[truststore.zip](https://github.com/shred/acme4j/files/1614275/truststore.zip)

**Comment by eknori** [comment]
Sorry, does not work. Same error: Caused by: java.io.IOException: Invalid keystore format

**Comment by eknori** [comment]
Would it be an idea not to use a local truststore but to let the user / developer import the certificate into the system cacerts?

**Comment by shred** [comment]
OK, it was worth a try... Thank you!

The Pebble cert should never be added to the system cacerts. The corresponding CA private key is intentionally made public, so it would be easy to generate all kind of fake SSL certificates that would be deemed valid by the system.

An alternative approach could be to read the PEM file to the `KeyStore` directly. Then we could completely avoid the openssl and keytool conversion. I'll have a look at that later. There are some other things I need to get completed first, before the official ACMEv2 launch in Februrary.

**Comment by eknori** [comment]
thx! no worries. I have a running environment now.

**Comment by vocsyurvish** [comment]
I have issue when i run apk as a debug.

**Comment by shred** [comment]
@vocsyurvish I'm sorry, but this problem is unrelated to _acme4j_. Maybe you will find help in an Android forum.

**Comment by vocsyurvish** [comment]
@shred Thankyou for suggestion :)
