### ISSUE TITLE
[ACME2] : "Failed to read certificate"

### ISSUE THREAD

**Issue by eknori** [shred/acme4j#60]
Hi,

I am trying to get a certificate using HTTP Challenge, but I am getting an error when acme4j tries to get the certificate

`2018-20-03 12:39:19.267 ERROR - STACK TRACE
org.shredzone.acme4j.exception.AcmeProtocolException: Failed to read certificate
	at org.shredzone.acme4j.connector.DefaultConnection.readCertificates(DefaultConnection.java:238)
	at org.shredzone.acme4j.Certificate.download(Certificate.java:71)
	at org.shredzone.acme4j.Certificate.lazyDownload(Certificate.java:207)
	at org.shredzone.acme4j.Certificate.getCertificate(Certificate.java:82)
	at de.midpoints.le4d.manager.Le4dManager.downloadCertificate(Le4dManager.java:433)
	at de.midpoints.le4d.manager.Le4dManager.orderCertificateUseHTTPChallenge(Le4dManager.java:393)
	at de.midpoints.le4d.manager.Le4dManager.process(Le4dManager.java:153)
	at de.midpoints.le4d.manager.Le4dManager.run(Le4dManager.java:117)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:44)
	at de.midpoints.le4d.runonstart.Le4d$1.doRun(Le4d.java:39)
	at de.midpoints.le4d.tools.SessionDatabase.runWithSessionAndDatabase(SessionDatabase.java:32)
	at de.midpoints.le4d.runonstart.Le4d.doRun(Le4d.java:39)
	at com.ibm.dots.task.AbstractServerTaskExt.run(AbstractServerTaskExt.java:47)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.doRun(JobTaskService.java:136)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.run(JobTaskService.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: insufficient data
	at com.ibm.security.x509.X509CertImpl.<init>(X509CertImpl.java:268)
	at com.ibm.crypto.provider.X509Factory.b(Unknown Source)
	at com.ibm.crypto.provider.X509Factory.engineGenerateCertificates(Unknown Source)
	at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:448)
	at org.shredzone.acme4j.connector.DefaultConnection.readCertificates(DefaultConnection.java:232)
	... 15 more

`

acme4j debug log is

`2018-20-03 12:39:13.930 DEBUG - create
2018-20-03 12:39:13.930 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/directory
2018-20-03 12:39:14.377 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:14.378 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:14.378 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:14.378 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:14.378 DEBUG - HEADER Server: nginx
2018-20-03 12:39:14.378 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:14.378 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:14.378 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:15 GMT
2018-20-03 12:39:14.378 DEBUG - HEADER Content-Length: 602
2018-20-03 12:39:14.378 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:15 GMT
2018-20-03 12:39:14.379 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:14.380 DEBUG - Result JSON: {"YE07SnbTCdg":"https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417","keyChange":"https://acme-staging-v02.api.letsencrypt.org/acme/key-change","meta":{"termsOfService":"https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"},"newAccount":"https://acme-staging-v02.api.letsencrypt.org/acme/new-acct","newNonce":"https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce","newOrder":"https://acme-staging-v02.api.letsencrypt.org/acme/new-order","revokeCert":"https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"}
2018-20-03 12:39:14.586 DEBUG - Replay Nonce: 4IRlJrfoX6Rfo-8XFutPnsfevjqbK8S0EWfI0sxSQx0
2018-20-03 12:39:14.603 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/new-acct
2018-20-03 12:39:14.603 DEBUG -   Payload: {"termsOfServiceAgreed":true}
2018-20-03 12:39:14.604 DEBUG -   JWS Header: {"nonce":"4IRlJrfoX6Rfo-8XFutPnsfevjqbK8S0EWfI0sxSQx0","url":"https://acme-staging-v02.api.letsencrypt.org/acme/new-acct","jwk":{"kty":"RSA","n":"nEyrDMS6lgYZq-rjAa01zcxCKnRM047fyOmGoWua4yBzjNfbMYA5ixBZ4ekSMXSI4mmy07uCFaZhgfhEVJTxcdPPJs7qdSAHctqLrnwPlm9BLYa6traUBVYrKAWu34TZDlgBwOMKqGxKZ-5bHKyD_SW69NnpMObuomVl7JwdPtXGA649TcJcI58Ju7oz6xGADZ3W1Y5YhzsbAvjjeiwP_f1L8_CVFZmpjZNqKsX_C2K0XHLFM9LMw-7rW_82nyXKLB9wt5q5cyphYVLmv83EC18AEYM8DdLkuIVYkqJp7_EXB3kz4VMtyasudNx3eyIgFcEhV4Tg8MTZGJnUbCPh4Q","e":"AQAB"},"alg":"RS256"}
2018-20-03 12:39:15.126 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:15.126 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:15.126 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:15.126 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:15.126 DEBUG - HEADER Server: nginx
2018-20-03 12:39:15.127 DEBUG - HEADER Replay-Nonce: Anrg65O8QkEP-HxyurbIk-5buWkF6CTSWNLpEdLZIfM
2018-20-03 12:39:15.127 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:15.127 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:15.127 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:15 GMT
2018-20-03 12:39:15.128 DEBUG - HEADER Content-Length: 0
2018-20-03 12:39:15.128 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:15 GMT
2018-20-03 12:39:15.128 DEBUG - HEADER Location: https://acme-staging-v02.api.letsencrypt.org/acme/acct/5773622
2018-20-03 12:39:15.128 DEBUG - Replay Nonce: Anrg65O8QkEP-HxyurbIk-5buWkF6CTSWNLpEdLZIfM
2018-20-03 12:39:15.128 DEBUG - Location: https://acme-staging-v02.api.letsencrypt.org/acme/acct/5773622
2018-20-03 12:39:15.131 DEBUG - create
2018-20-03 12:39:15.146 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/new-order
2018-20-03 12:39:15.146 DEBUG -   Payload: {"identifiers":[{"type":"dns","value":"midpoints.spdns.de"}]}
2018-20-03 12:39:15.146 DEBUG -   JWS Header: {"nonce":"Anrg65O8QkEP-HxyurbIk-5buWkF6CTSWNLpEdLZIfM","url":"https://acme-staging-v02.api.letsencrypt.org/acme/new-order","kid":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/5773622","alg":"RS256"}
2018-20-03 12:39:15.368 DEBUG - HEADER null: HTTP/1.1 201 Created
2018-20-03 12:39:15.368 DEBUG - HEADER Server: nginx
2018-20-03 12:39:15.368 DEBUG - HEADER Replay-Nonce: FOE7hbGJHhr1e0VwdJQU_9iIACM9xzncgkeyeEGiD74
2018-20-03 12:39:15.368 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:15.368 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:15.368 DEBUG - HEADER Boulder-Requester: 5773622
2018-20-03 12:39:15.368 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.368 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:15.368 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:15.369 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:15.369 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.369 DEBUG - HEADER Content-Length: 389
2018-20-03 12:39:15.369 DEBUG - HEADER Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/5773622/100976
2018-20-03 12:39:15.369 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:15.369 DEBUG - Replay Nonce: FOE7hbGJHhr1e0VwdJQU_9iIACM9xzncgkeyeEGiD74
2018-20-03 12:39:15.369 DEBUG - Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/5773622/100976
2018-20-03 12:39:15.370 DEBUG - Result JSON: {"status":"pending","expires":"2018-03-27T11:39:16.150341542Z","identifiers":[{"type":"dns","value":"midpoints.spdns.de"}],"authorizations":["https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k"],"finalize":"https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5773622/100976"}
2018-20-03 12:39:15.370 DEBUG - update Authorization
2018-20-03 12:39:15.370 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k
2018-20-03 12:39:15.577 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:15.577 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:15.578 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:15.578 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:15.578 DEBUG - HEADER Server: nginx
2018-20-03 12:39:15.578 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:15.578 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:15.578 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.578 DEBUG - HEADER Content-Length: 1024
2018-20-03 12:39:15.578 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.578 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:15.579 DEBUG - Result JSON: {"identifier":{"type":"dns","value":"midpoints.spdns.de"},"status":"valid","expires":"2018-04-19T11:24:36Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722823","token":"updkWCZbQyc3NpzvP-dI0oEs-Wh_7UnfreK2POo7J6Q"},{"type":"http-01","status":"valid","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824","token":"0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","validationRecord":[{"url":"http://midpoints.spdns.de/.well-known/acme-challenge/0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","hostname":"midpoints.spdns.de","port":"80","addressesResolved":["77.181.49.159"],"addressUsed":"77.181.49.159"}]}]}
2018-20-03 12:39:15.583 DEBUG - trigger
2018-20-03 12:39:15.597 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824
2018-20-03 12:39:15.597 DEBUG -   Payload: {"keyAuthorization":"0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE.VB46BE0-T0pno9z28EzVrXQIHdXyUyX9qwIVUqtMTs8"}
2018-20-03 12:39:15.597 DEBUG -   JWS Header: {"nonce":"FOE7hbGJHhr1e0VwdJQU_9iIACM9xzncgkeyeEGiD74","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824","kid":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/5773622","alg":"RS256"}
2018-20-03 12:39:15.809 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:15.809 DEBUG - HEADER Server: nginx
2018-20-03 12:39:15.809 DEBUG - HEADER Replay-Nonce: vErta0Lg5ORtL4WaNP1_HmHmJFEyUkF6OHU9YtMeMtc
2018-20-03 12:39:15.809 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:15.809 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:15.809 DEBUG - HEADER Boulder-Requester: 5773622
2018-20-03 12:39:15.809 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.810 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:15.810 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:15.810 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:15.810 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:16 GMT
2018-20-03 12:39:15.810 DEBUG - HEADER Content-Length: 541
2018-20-03 12:39:15.810 DEBUG - HEADER Link: <https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k>;rel="up"
2018-20-03 12:39:15.810 DEBUG - HEADER Location: https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824
2018-20-03 12:39:15.810 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:15.810 DEBUG - Replay Nonce: vErta0Lg5ORtL4WaNP1_HmHmJFEyUkF6OHU9YtMeMtc
2018-20-03 12:39:15.811 DEBUG - Result JSON: {"type":"http-01","status":"valid","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824","token":"0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","validationRecord":[{"url":"http://midpoints.spdns.de/.well-known/acme-challenge/0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","hostname":"midpoints.spdns.de","port":"80","addressesResolved":["77.181.49.159"],"addressUsed":"77.181.49.159"}]}
2018-20-03 12:39:16.813 DEBUG - update Authorization
2018-20-03 12:39:16.813 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k
2018-20-03 12:39:17.026 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:17.026 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:17.028 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:17.029 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:17.029 DEBUG - HEADER Server: nginx
2018-20-03 12:39:17.029 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:17.030 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:17.030 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:17 GMT
2018-20-03 12:39:17.031 DEBUG - HEADER Content-Length: 1024
2018-20-03 12:39:17.031 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:17 GMT
2018-20-03 12:39:17.031 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:17.032 DEBUG - Result JSON: {"identifier":{"type":"dns","value":"midpoints.spdns.de"},"status":"valid","expires":"2018-04-19T11:24:36Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722823","token":"updkWCZbQyc3NpzvP-dI0oEs-Wh_7UnfreK2POo7J6Q"},{"type":"http-01","status":"valid","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k/110722824","token":"0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","validationRecord":[{"url":"http://midpoints.spdns.de/.well-known/acme-challenge/0CYdp5GTuu0OnBOLcgGaRgExJ0SR22d8omq8VteAyeE","hostname":"midpoints.spdns.de","port":"80","addressesResolved":["77.181.49.159"],"addressUsed":"77.181.49.159"}]}]}
2018-20-03 12:39:17.053 DEBUG - finalize
2018-20-03 12:39:17.069 DEBUG - POST https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5773622/100976
2018-20-03 12:39:17.070 DEBUG -   Payload: {"csr":"MIICkjCCAXoCAQAwHTEbMBkGA1UEAwwSbWlkcG9pbnRzLnNwZG5zLmRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo_ZWeMPtw34K-fcdKdqe5sT9xixBWMbI4cvoQVVyl5vyrVD8KRQjuD_atnu5bAefy5IH9eWdXN_XSyRwIDBBBWvapWBOy-rsOieRdPdrzloKrGR2UXVuWY_xlcfnlTChwVyJlyVUq2FVfW80tLX5pDOsBRkq4Kq3Gqz2Py6tNlPiDvNUo_CcpXfkWFJr1z8MfBQJGLgSGhQ-UCvf8bhmFoEhOc_u9qjGaKkvOe8QLt8JlcD5JW4J_1e-l_-4bsQh7K9zat6gvDxc3zulBbZzswGv9jhJlhB7P8xBRMhwIILMdIVjNU1U4BbyXbp6DJth9lrC9Y4yAMYVOmGRruuJfQIDAQABoDAwLgYJKoZIhvcNAQkOMSEwHzAdBgNVHREEFjAUghJtaWRwb2ludHMuc3BkbnMuZGUwDQYJKoZIhvcNAQELBQADggEBAByTINQjeisbjJZm0t83N70DnK-a4sMcyyuFFdU2ygV105XhOIdkKZID13WIk97autYJrmd8AlA7kDBi4mBlS2SY2ynjkBdWsczrr1ZKe9DlsgM2OXFqHH94MxGpJ4moW7B-M6DktlRQ_H1pmO5lCq8E5GP9XuDPw9mO1cNgFIUCPSBuJl1MRi0FknyJ5J9DdthxZuiPRL3HO-3c121hWP2thKZzZWgdnuS1bTR2LfdH0xnxRRyDoMxMVTxi4wRqVcSVTfDUg2wmOQ66OTJnlEc_NuCT8UXUcLgo9s03k__8Vfcp0_NPjeyE3elUzSkyfCXcvWnIWHM_Jb-TMF8EkHg"}
2018-20-03 12:39:17.070 DEBUG -   JWS Header: {"nonce":"vErta0Lg5ORtL4WaNP1_HmHmJFEyUkF6OHU9YtMeMtc","url":"https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5773622/100976","kid":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/5773622","alg":"RS256"}
2018-20-03 12:39:17.583 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:17.583 DEBUG - HEADER Server: nginx
2018-20-03 12:39:17.584 DEBUG - HEADER Replay-Nonce: lqRTJbowzMIb5FKpNxR_O1lx2zDI5qbHkl4bhx4jywg
2018-20-03 12:39:17.584 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:17.584 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:17.584 DEBUG - HEADER Boulder-Requester: 5773622
2018-20-03 12:39:17.585 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:18 GMT
2018-20-03 12:39:17.585 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:17.585 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:17.585 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:17.585 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:18 GMT
2018-20-03 12:39:17.585 DEBUG - HEADER Content-Length: 489
2018-20-03 12:39:17.585 DEBUG - HEADER Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/5773622/100976
2018-20-03 12:39:17.585 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:17.586 DEBUG - Replay Nonce: lqRTJbowzMIb5FKpNxR_O1lx2zDI5qbHkl4bhx4jywg
2018-20-03 12:39:18.586 DEBUG - update Order
2018-20-03 12:39:18.587 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/acme/order/5773622/100976
2018-20-03 12:39:18.846 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:18.846 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:18.846 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:18.846 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:18.846 DEBUG - HEADER Server: nginx
2018-20-03 12:39:18.846 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:18.846 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:18.846 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:19 GMT
2018-20-03 12:39:18.846 DEBUG - HEADER Content-Length: 489
2018-20-03 12:39:18.847 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:19 GMT
2018-20-03 12:39:18.847 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:18.847 DEBUG - Result JSON: {"status":"valid","expires":"2018-03-27T11:39:16Z","identifiers":[{"type":"dns","value":"midpoints.spdns.de"}],"authorizations":["https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k"],"finalize":"https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5773622/100976","certificate":"https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa9a442da786ee5d87ad37d6dd3bbfac22db"}
2018-20-03 12:39:18.848 DEBUG - update Order
2018-20-03 12:39:18.848 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/acme/order/5773622/100976
2018-20-03 12:39:19.054 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:19.055 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:19.055 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:19.055 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:19.055 DEBUG - HEADER Server: nginx
2018-20-03 12:39:19.055 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:19.056 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:19.056 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:19 GMT
2018-20-03 12:39:19.056 DEBUG - HEADER Content-Length: 489
2018-20-03 12:39:19.056 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:19 GMT
2018-20-03 12:39:19.056 DEBUG - HEADER Content-Type: application/json
2018-20-03 12:39:19.057 DEBUG - Result JSON: {"status":"valid","expires":"2018-03-27T11:39:16Z","identifiers":[{"type":"dns","value":"midpoints.spdns.de"}],"authorizations":["https://acme-staging-v02.api.letsencrypt.org/acme/authz/pR283zYndZDx1cfVWQc5PBuPRfBb5ZfsfAq4HGtrj9k"],"finalize":"https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5773622/100976","certificate":"https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa9a442da786ee5d87ad37d6dd3bbfac22db"}
2018-20-03 12:39:19.057 DEBUG - download
2018-20-03 12:39:19.057 DEBUG - GET https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa9a442da786ee5d87ad37d6dd3bbfac22db
2018-20-03 12:39:19.263 DEBUG - HEADER X-Frame-Options: DENY
2018-20-03 12:39:19.263 DEBUG - HEADER null: HTTP/1.1 200 OK
2018-20-03 12:39:19.263 DEBUG - HEADER Strict-Transport-Security: max-age=604800
2018-20-03 12:39:19.264 DEBUG - HEADER Cache-Control: max-age=0, no-cache, no-store
2018-20-03 12:39:19.264 DEBUG - HEADER Server: nginx
2018-20-03 12:39:19.264 DEBUG - HEADER Connection: keep-alive
2018-20-03 12:39:19.264 DEBUG - HEADER Pragma: no-cache
2018-20-03 12:39:19.264 DEBUG - HEADER Expires: Tue, 20 Mar 2018 11:39:20 GMT
2018-20-03 12:39:19.264 DEBUG - HEADER Content-Length: 3798
2018-20-03 12:39:19.264 DEBUG - HEADER Date: Tue, 20 Mar 2018 11:39:20 GMT
2018-20-03 12:39:19.264 DEBUG - HEADER Content-Type: application/pem-certificate-chain

`

Anything, I am missing?

**Comment by shred** [comment]
It seems to be a problem with IBM's crypto implementation. According to http://www-01.ibm.com/support/docview.wss?uid=swg21433373 the PEM header is missing or malformed.

You can download your certificate directly from here (e.g. via `curl`): https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa9a442da786ee5d87ad37d6dd3bbfac22db

If you have a look at the cert, you will see that there are multiple sections in it. You can download it and then try to load it in a test class, e.g.:

```java
try (InputStream in = new FileInputStream("your-cert.csr") {
    CertificateFactory cf = CertificateFactory.getInstance("X.509");
    cf.generateCertificates(in);
}
```

Then try to alter the csr file in a text editor, and see if you can make it work. My gut feeling is that the IBM implementation has a problem with the empty line between an `END CERTIFICATE` and the next `BEGIN CERTIFICATE`.

**Comment by shred** [comment]
I've tried it with OpenJ9, but could not reproduce it. If you find a fix, please let me know.

**Comment by eknori** [comment]
Thx for the update. Will look into it tomorrow morning. 
BTW. It works with ACME 1 on the same machine.

**Comment by shred** [comment]
In ACME v1, the certificate and intermediates were transmitted in separate resources. It is merged into one resource since ACME v2. This is why I suspect the empty line.

**Comment by eknori** [comment]
I have changed the code in class DefaultConnection

`	@Override
	public List<X509Certificate> readCertificates() throws AcmeException {
		assertConnectionIsOpen();
		String contentType = AcmeUtils.getContentType(conn.getHeaderField(CONTENT_TYPE_HEADER));
		if (!("application/pem-certificate-chain".equals(contentType))) {
			throw new AcmeProtocolException("Unexpected content type: " + contentType);
		}
		try (InputStream in = conn.getInputStream()) {

			StringBuffer sb = new StringBuffer();
			BufferedReader br = new BufferedReader(new InputStreamReader(in, "UTF-8"));
			String line;
			while ((line = br.readLine()) != null) {
				if (line.trim().length() == 0) {
					continue; // Skip blank lines
				} else {
					sb.append(line);
					sb.append("\n");
				}
			}

			br.close();

			ByteArrayInputStream bytes = new ByteArrayInputStream(sb.toString().getBytes("UTF-8"));
			CertificateFactory cf = CertificateFactory.getInstance("X.509");

			return cf.generateCertificates(bytes).stream().map(c -> (X509Certificate) c).collect(toList());
		} catch (IOException ex) {
			throw new AcmeNetworkException(ex);
		} catch (CertificateException ex) {
			throw new AcmeProtocolException("Failed to read certificate", ex);
		}
	}`

This does the trick. I guess that there is a more elegant way to remove the blank lines :)

**Comment by shred** [comment]
Allright... I will implement an `InputStream` filter, to keep the memory footprint small.

**Comment by shred** [comment]
Commit 3f901e9e should fix this problem. Can you give it a try?

**Comment by eknori** [comment]
Excellent. That fixes it.
