### ISSUE TITLE
Deactivate fully TLS server certificate checks on Pebble provider

### ISSUE THREAD

**Issue by aloopkin** [shred/acme4j#72]
Hello,

The current acme4j "Pebble" provider implementation embeds the pebble TLS server certificate in the code in order to trust the connection. This works well if Pebble is on the same machine as the acme4j client...
Could you instead fully deactivate the TLS check ? this could be done by the following code:
```
			TrustManager[] tmf = new TrustManager[] { new X509TrustManager() {
				@Override
				public java.security.cert.X509Certificate[] getAcceptedIssuers() {
					return new java.security.cert.X509Certificate[] {};
				}

				@Override
				public void checkClientTrusted(
						java.security.cert.X509Certificate[] certs,
						String authType) {
				}

				@Override
				public void checkServerTrusted(
						java.security.cert.X509Certificate[] certs,
						String authType) {
				}
			} };

```

Regards,
Alexandre

**Comment by shred** [comment]
Can you explain a little more?

There should be no problem with the existing certificate check, even if Pebble is running on a different machine. For example, I let Pebble run on a docker container for integration tests, and it is still working fine.

**Comment by aloopkin** [comment]
Well, that's not what i get, obviously:
org.shredzone.acme4j.exception.AcmeNetworkException: Network error
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:315)
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:140)
	at org.shredzone.acme4j.provider.AbstractAcmeProvider.directory(AbstractAcmeProvider.java:58)
	at org.shredzone.acme4j.Session.readDirectory(Session.java:228)
	at org.shredzone.acme4j.Session.getMetadata(Session.java:211)
	at com.etrustforge.connectors.pki.impl.ACMEConnector.findOrRegisterAccount(ACMEConnector.java:259)
	... 53 more
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 192.168.X.Y found
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:300)

**Comment by cpu** [comment]
> No subject alternative names matching IP address 192.168.X.Y found

The default `test/certs/localhost/cert.pem` leaf certificate used by Pebble only has subject alternate names for: `localhost`, `pebble`, and the IP `127.0.0.1`.

@aloopkin I think your best solution is either:
1) Add a hosts entry or some kind of mock DNS that allows you to connect to the Pebble instance by the domain name `pebble` instead of the raw IP `192.168.x.x`
2) Use the `test/pebble.minica.key.pem` private key and `test/pebble.minica.pem` certificate to issue a new leaf certificate that includes a SAN for your local IP address `192.168.x.x`. You can use [MiniCA](https://github.com/jsha/minica/) for this.

I believe either option will work without changing ACME4J since it trusts the `test/pebble.minica.pem` root certificate.

**Comment by shred** [comment]
Turning off all TLS checks is always my least favorite option. It's sufficient to use a `HostnameVerifier` that accepts all host names. This way, Pebble's certificate is still checked, but it does not need to come from `localhost`, `pebble` or `127.0.0.1` any more. I think that this is not a security problem here, since Pebble instances are only used in local development and testing environments.

The modified Pebble connector will be available in _acme4j_ v2.6, see commit 1e506699998d8bc0dc9451aa64bb76ac2e538cd4. If you cannot wait, you can also use one of the solutions proposed by @cpu.

**Comment by aloopkin** [comment]
Thanks, works for me indeed! Actually, for now i worked it around using ssh -L.

**Comment by shred** [comment]
Thank you for reporting this issue. The Pebble connector was always intended to work like it is now.
